services:
  custom-nginx:
    build: .
    container_name: custom-nginx
    ports:
      - "80:80"
    volumes:
      - nginx-data:/var/opt/nginx
    restart: unless-stopped

volumes:
  nginx-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/opt/nginx
